### ISSUE TITLE
Construct Response Probability

### ISSUE THREAD

**Issue by thesentinel2615** [WaywardWyvernsSoftworks/ConstructOS#10]
**Is your feature request related to a problem? Please describe.**
The current random response percentages are shit and inconsistent. I want some Constructs to reply all of the time, and want others to reply only when mentioned by name.

**Describe the solution you'd like**
Allowing users to customize the chance for a specific Construct to reply to:
A) another Construct. 
B) When another Construct mentions them. 
C) A User. 
D) When a user mentions them.

Add in a new object to the ChatLog object that looks like this:
```ts
interface ConstructConfig {
  doLurk: boolean;
  haveThoughts: boolean;
  thinkBeforeChat: boolean;
  replyToConstruct: number;
  replyToConstructMention: number;
  replyToUser: number;
  replyToUserMention: number;
  _id: number;
}
```

These values should be appended to array, the array containing the ConstructConfig for each Construct inside of the Chat. These should editable from inside of the Chat UI, and inside of the Discord Bot via command. There should be both a global default ConstructConfig and Construct specific default config.

**Comment by alicat22** [comment]
Regarding the above, I'm still testing. I think it largely depends on context because having a bot continue to generate ongoing is quite nice; however, if I'm doing more involved roleplay, having it out of order can derail the conversation quite quickly.
